@startuml

start

:Автомобиль поступает на конвеер;
repeat :Проводятся работы производства автомобиля;
repeat :Проводятся работы этапа ковеера;
  if (Были выявлены дефекты) then (Да) 
    :вызов ремонт>
  endif
  :Автомобиль проходит дальше по ковееру;
repeat while (Остались непройденные этапы конвеера?) is (Да)
-> Нет;
:Автомобиль проходит тесты в контроле качества;
if (Были выявлены дефекты) then (Да) 
  :вызов ремонт>
endif
repeat while (На тестах были выявлены дефекты) is (Да)
-> Нет;
:Автомобиль отгружается заказчику;
stop

partition ремонт {
    :Автомобиль отправляется в ремонтную зону;
    :Бригадир назначает рабочему задачу устранения дефектов;
    :Диспетчер направляет автомобиль на ремонтное место;
    :Рабочий устраняет дефекты;
    :Рабочий вносит от по проделанной работе;
    :Автомобиль возвращается на конвеер;
}
@enduml
