@startuml


actor Диспетчер
actor Рабочий
actor Бригадир
actor "Начальник цеха"
actor "Отдел контроля качества"
actor Бухгалтерия

Диспетчер -r-> (Внесение данных о ремонтных зонах, ремонтных местах, ремонтных бригадах и их бригадирах)
Диспетчер --> (Мониторинг занятости рабочих, ремонтных мест и прогресса ремонта)
Диспетчер --> (Назначение автомобиля в ремонтную зону)

Рабочий -l-> (Регистрация дефекта)
Рабочий -r-> (Регистрация ремонта)

Бригадир -r-> (Назначение ремонта работнику)
Бригадир -u-> (Мониторинг занятости рабочих, ремонтных мест и прогресса ремонта)
Бригадир -d-> (Сформировать отчет)

"Начальник цеха" -r-> (Сформировать отчет)

"Отдел контроля качества" -u-> (Сформировать отчет)
"Отдел контроля качества" --> (Внесение результатов тестов в систему)
"Отдел контроля качества" -d-> (Регистрация дефекта)

Бухгалтерия -l-> (Сформировать отчет)


@enduml
